version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  api:
    build: .
    container_name: node_api
    environment:
      MONGODB_URI: mongodb://mongo:27017/transacciones
      PORT: 3002  # Cambia el puerto a 3002
    ports:
      - "3002:3002"  # Expon el puerto 3002
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
